database:
  db_file: resources/object_paths.db
  record_paths: False
yolo:
  device: cuda
  version: yolov5xu.pt
  imgsz: 640
deepsort:
  max_disappeared: 100
  max_distance: 30
  device: "cuda"
  appearance_weight: 0.5
  motion_weight: 0.5