database:
  db_file: resources/object_paths.db
  record_paths: False
inference:
  max_frame_gap: 5.0
  max_latency: 0.5
  skip_frames: 2
yolo:
  device: cuda
  version: yolov5xu.pt
  imgsz: 640
deepsort:
  max_disappeared: 50
  max_distance: 100
  device: "cuda"
  appearance_weight: 0.5
  motion_weight: 0.5