yolo:
  device: cuda
  version: yolov5m.pt
  imgsz: 640

  conf: 0.30
  classes: [0,1,2,3,5,7]
  conf_per_class:
    0: 0.30
    2: 0.40
  
database:
  db_file: resources/object_paths.db
  record_paths: False

deepsort:
  max_disappeared: 40
  max_distance: 15
  device: "cuda"
  appearance_weight: 0.5
  motion_weight: 0.5

detection_thread:
  detection_fps: 15
  delay_seconds: 5.0

crosswalk_monitor:
  traffic_light_fps: 20