yolo:
  device: cuda
  version: yolov5m.pt
  imgsz: 640

  conf: 0.2
  classes: [0,1,2,3,5,7]
  conf_per_class:
    0: 0.2
    1: 0.70
    2: 0.2
  
database:
  db_file: resources/object_paths.db
  record_paths: False

deepsort:
  max_disappeared: 40
  max_distance: 10
  device: "cuda"

  appearance_weight: 0.4
  motion_weight: 0.4
  iou_weight: 0.2

  nn_budget: 100

detection_thread:
  detection_fps: 10
  delay_seconds: 5.0

crosswalk_monitor:
  traffic_light_fps: 20