database:
  db_file: resources/object_paths.db
  record_paths: False
yolo:
  device: cuda
  version: yolov5n.pt
  imgsz: 640
deepsort:
  max_disappeared: 50
  max_distance: 30
  device: "cuda"
  appearance_weight: 0.7
  motion_weight: 0.3